### ISSUE TITLE
[Improvement] Reduce size of docker image

### ISSUE THREAD

**Issue by mpvartak** [VertaAI/modeldb#213]
Current image is several GBs. Can we reduce?

**Comment by justinanderson** [comment]
My plan here is to split ModelDB into multiple Docker images. Dockerized projects typically run one service per image, so services can be started/stopped/upgraded at the container level rather than having to shell into them and keep track of what's changed from the image.

I was thinking four images:
1. [Official MongoDB](https://hub.docker.com/_/mongo/)
2. Backend Java app and SQLite
3. Frontend NodeJS app
4. Pre-built ModelDB client libraries

The [current monolithic image](https://hub.docker.com/r/sanjayganeshan/mdgmodeldb/tags/) on Docker Hub is 5 GB. A server made of split images would only need about 2.5 GB: MongoDB (0.3 GB), backend (1.3 GB), and frontend (0.9 GB).

We could shrink the total another 0.5 GB by removing the Thrift compiler from images after it has served its purpose, but then incremental dev builds would take a long time. That's something to think about for production builds if we want to be aggressive about image sizes.

I'll include a Docker Compose file so end users only need to run `docker-compose up` to get a server going.

Thoughts?

**Comment by ghost** [comment]
I strongly support going the microservices route as you've suggested. At Scotiabank we were already talking about splitting up the repo into frontend, server, and client containers to achieve our aims - separating out MongoDB makes sense as well.

**Comment by mpvartak** [comment]
@shubhamchopra @skadambi thoughts?
