### ISSUE TITLE
Cannot Deploy on AKS using Helm Chart

### ISSUE THREAD

**Issue by NishkarshRaj** [VertaAI/modeldb#2248]
Hi, I am trying to deploy ModelDB on Azure Kubernetes Services with K8s 1.19 but I am getting the following error:

```
nishkarshraj@Azure:~/modeldb/chart/modeldb$ pwd
/home/nishkarshraj/modeldb/chart/modeldb

nishkarshraj@Azure:~/modeldb/chart/modeldb$ git remote -v
origin  https://github.com/VertaAI/modeldb (fetch)
origin  https://github.com/VertaAI/modeldb (push)

nishkarshraj@Azure:~/modeldb/chart/modeldb$ pwd
/home/nishkarshraj/modeldb/chart/modeldb

nishkarshraj@Azure:~/modeldb/chart/modeldb$ ls
charts  Chart.yaml  README.md

nishkarshraj@Azure:~/modeldb/chart/modeldb$ helm install . --name rel1 --namespace default
Error: unknown flag: --name
```

Please help me out.

**Comment by convoliution** [comment]
Hi @NishkarshRaj,

It appears that your system may be using Helm v3, which does not have the `--name` flag. You might find success with
```bash
$ helm install rel1 . --namespace default
```

[This StackOverflow post](https://stackoverflow.com/questions/57961162/helm-install-unknown-flag-name) has some relevant details.

Since this appears to be a Helm issue rather than a ModelDB issue, I will be closing this unless we can be of further assistance here. Please let me know!

**Comment by convoliution** [comment]
I've just noticed the PR you opened for this, thank you!
