### ISSUE TITLE
Pyyaml vulnerability in verta client

### ISSUE THREAD

**Issue by Atharex** [VertaAI/modeldb#2379]
The verta client is using a version of pyyaml (< 5.4) which has a RCE vulnerability
https://github.com/VertaAI/modeldb/blob/master/client/verta/setup.py#L34

The SNYK security scanner rates it as a very critical problem (CVSS 9.8/10)
https://snyk.io/vuln/pip:pyyaml

The suggested fix is to upgrade pyyaml to at least version 5.4
https://snyk.io/vuln/SNYK-PYTHON-PYYAML-590151

**Comment by convoliution** [comment]
Thank you, @Atharex! I'll check that 5.4's [changes](https://github.com/yaml/pyyaml/blob/58d0cb7ee09954c67fabfbd714c5673b03e7a9e1/announcement.msg#L24-L31) don't break anything, and hopefully have this upgraded in one of next releases.

And a note for myself:

> PyYAML 5.4.1 will be the last release to support Python 2.7 (except for possible critical bug fix releases).

—https://github.com/yaml/pyyaml/blob/ee37f46/announcement.msg#L15-L16

So that may need to be the new upper bound

**Comment by convoliution** [comment]
As I was doing a follow-up investigation into this, I realized that the security advisory for `pyyaml<5.4` cites a vulnerability in `full_load()` and `FullLoader`. Fortunately for us and our users, the client diligently uses `safe_load()` everywhere, _which is incapable of the cautioned arbitrary code execution_.

In light of that, **I am considering this a non-critical issue**, but we _should still_ increase the upper bound on our `pyyaml` version constraint so that users can install a safer version in their Python environment without conflicting with our library.
