### ISSUE TITLE
host=localhost not possible with docker mac

### ISSUE THREAD

**Issue by soellingeraj** [VertaAI/modeldb#258]
Not sure if anyone else has experienced this same issue.

I am using the docker-compose modeldb installation on a mac, and unable to connect the docker-machine to localhost.  Here's another forum discussing the issue: https://forums.docker.com/t/using-localhost-for-to-access-running-container/3148

As a workaround, I used this script for the [path to modeldb directory] that find/replaces all the instances of localhost in the routing files.

```
sed -i -e 's/localhost/<docker-machine address>/g' server/src/main/resources/reference.conf
sed -i -e 's/localhost/<docker-machine address>/g' server/src/main/resources/reference-docker.conf
sed -i -e 's/localhost/<docker-machine address>/g' server/src/main/resources/reference-test.conf
sed -i -e 's/localhost/<docker-machine address>/g' client/syncer.json
sed -i -e 's/localhost/<docker-machine address>/g' frontend/util/check_thrift.js
sed -i -e 's/localhost/<docker-machine address>/g' frontend/util/thrift.js
sed -i -e 's/localhost/<docker-machine address>/g' client/python/modeldb/basic/Structs.py
```

For <docker-machine address>, do: $ docker-machine ls

```
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER        ERRORS
default   -        virtualbox   Running   tcp://192.168.99.100:2376           v17.05.0-ce   
```

After that I was able to add new projects to the docker/modeldb.

I can branch and submit a pull request.  Or, is there a better way?  Please advise.

**Comment by mpvartak** [comment]
@justinanderson

**Comment by justinanderson** [comment]
Hi @soellingeraj, it sounds like you're using the older Docker Toolbox instead of Docker for Mac. If your system supports it, I recommend [switching to Docker for Mac](https://docs.docker.com/docker-for-mac/docker-toolbox/). It doesn't use virtualbox anymore and so removes many of the headaches like port forwarding involved with Docker development on a Mac.

If you use Docker for Mac, it will forward all exposed container ports to localhost automatically. `docker-compose up` should leave you with a web server reachable at http://localhost:3000/ and a `docker-machine ls` that looks like this:

```
NAME      ACTIVE   DRIVER       STATE     URL   SWARM   DOCKER    ERRORS
default   -        virtualbox   Stopped                 Unknown
```

If you need to run Docker Toolbox, I suggest setting up port forwarding for the virtualbox VM used by docker-machine, as detailed in this [Stack Overflow answer](https://stackoverflow.com/a/35374087/85337).

**Comment by soellingeraj** [comment]
thank you.  that worked.
you can close this one.
