### ISSUE TITLE
What the status of ModelDB project is?

### ISSUE THREAD

**Issue by YujiOshima** [VertaAI/modeldb#290]
Hi! @mpvartak 
I'm from [kubeflow/katib](https://github.com/kubeflow/katib).
We are using modelDB in our project.
And we have some requests for this project.
But this project does not active since Feb.
Could we get involved in the development of ModelDB and help to maintain it?

**Comment by mpvartak** [comment]
Hi there, thanks for pinging! Absolutely, we'd be super interested in getting more contributors to help maintain modeldb. We're in the middle of a transition, so things have been slow. What's the best way to reach you? Please feel free to email at mvartak_at_csail.mit.edu.

PS: Katib looks really good!

**Comment by gaocegege** [comment]
@mpvartak 

Thanks for your reply! We ([Kubeflow](https://github.com/kubeflow) guys) have a [slack channel](https://join.slack.com/t/kubeflow/shared_invite/enQtMjgyMzMxNDgyMTQ5LWUwMTIxNmZlZTk2NGU0MmFiNDE4YWJiMzFiOGNkZGZjZmRlNTExNmUwMmQ2NzMwYzk5YzQxOWQyODBlZGY2OTg). @YujiOshima and me, maintainers of katib, usually discuss in the topic [#hyperparameter-tuning](https://kubeflow.slack.com/messages/C9ZLKR73L/details/). Thus we prefer to use Slack if you do not mind since there are other people also interested in the project.

As @YujiOshima said, we are using modeldb for model management. And we found some pain points from our side to be enhanced or implemented:

> * not user-friendly API. We need to maintain go thrift interfaces.
> * Data can not be deleted from DB.

We are glad to help modeldb in the things that we are interetsed in first, to demonstrate our knowledge on modeldb code base. And as the development of katib is going on, maybe we need some more features from modeldb. We hope that we could collaborate deeply. We could discuss about how to achieve it via slack or email, e.g. outside collaborator or we file PR then request owner's review.

BTW, thanks for your awesome work on model management! 🎉 😄

**Comment by jlewi** [comment]
I'm experimenting with using Model DB to track experiments/models in Kubeflow and I ran into some problems accessing the data in the UI:

kubeflow/examples#134

Any help would be greatly appreciated.

**Comment by bhack** [comment]
@jlewi Do you think that Model DB needs to be forked?

**Comment by jlewi** [comment]
I think forking is premature.

What are the features/fixes that we want?
Do we have folks in the Kubeflow community to work on this?

I don't think we Kubeflow have really started trying to tap into modelDB
yet.  So my highest priority would be trying to leverage modelDB and seeing
whats Missing for our use cases.

**Comment by mpvartak** [comment]
@jlewi responded to your comment on Kubeflow repo. Need to repro your bug and will update.

**Comment by ryandawsonuk** [comment]
The README says that V2 is coming soon but there hasn't been a commit to master for 9 months and I don't see any active branches. Is this project still actively maintained? Anyone have any insight?

**Comment by gaocegege** [comment]
Same question. I cannot see any progress here.

**Comment by mpvartak** [comment]
Hi all -- we have been developing the project under VertaAI (https://github.com/VertaAI/) -- the company we started around ModelDB. We are actively maintaining it the OSS fork there while we figure out the best way to update the MIT repo too (since it's a different org). We should have this sorted out by end of year, but for now, please check out the VertaAI repos, they are up-to-date. Also happy to get you set up with a trial account on VertaAI, please send me at note!

**Comment by ryandawsonuk** [comment]
Ok so basically https://github.com/VertaAI/modeldb is how to run V2 and the other repos there are components of V2?
