### ISSUE TITLE
Is there a way to identify relationships between all database tables ?

### ISSUE THREAD

**Issue by robbine** [VertaAI/modeldb#558]
Hi, I'm curious about modeldb backend design. 
For example, table 'dateset_version' has three column constraints with 'path_dataset_version_info', 'query_dataset_version_info', 'raw_dataset_version_info' respectively.
Is there some specific reason for this design ?
Many thanks !

**Comment by mvartakAtVerta** [comment]
Hi @robbine, thanks for the question! Our data versioning structure is currently in flux so this table structure is going to change in the coming weeks. At a high level, our DB is designed to handle different types of datasets, so that's the structure you see.

If you have any ideas/suggestions on DB design, please chime in here or on our Slack channel (http://bit.ly/modeldb-mlops).

**Comment by ravishetye** [comment]
To add to what @mvartakAtVerta mentioned and to address the updated title, the foreign key constraints can be found spread across the files in the [liquibase folder ](https://github.com/VertaAI/modeldb/tree/ebc029a92e36bbe0c78ad975836aa8465673852f/backend/src/main/resources/liquibase)

**Comment by robbine** [comment]
@ravishetye @mvartakAtVerta ,
The reason I asked this question is because I find there are some replicated columns across tables. And of course we can discuss them on the Slack channel , so I will close the issue.
Thanks for your replies !
